name: Deploy to IONOS via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install lftp
      run: sudo apt-get update && sudo apt-get install -y lftp

    - name: Generate config.php from secrets
      env:
        DB_HOST: ${{ secrets.SPARK_DBHOST }}
        DB_NAME: ${{ secrets.SPARK_DBNAME }}
        DB_USER: ${{ secrets.SPARK_DBUSERNAME }}
        DB_PASS: ${{ secrets.SPARK_DBPASSWORD }}
      run: |
        cat <<EOF > config.php
<?php
define('DB_HOST', '${DB_HOST}');
define('DB_NAME', '${DB_NAME}');
define('DB_USER', '${DB_USER}');
define('DB_PASS', '${DB_PASS}');

\$pdo = new PDO("mysql:host=" . DB_HOST . ";dbname=" . DB_NAME, DB_USER, DB_PASS);
\$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
?>
EOF

    - name: Deploy via SFTP
      env:
        SFTP_HOST: ${{ secrets.SFTP_HOST }}
        SFTP_PORT: ${{ secrets.SFTP_PORT }}
        SFTP_USER: ${{ secrets.SFTP_USER }}
        SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        SFTP_TARGET_DIR: ${{ secrets.SFTP_TARGET_DIR }}
      run: |
        lftp -e "
          set sftp:auto-confirm yes;
          open -u $SFTP_USER,$SFTP_PASSWORD -p $SFTP_PORT sftp://$SFTP_HOST;
          mirror -R ./ $SFTP_TARGET_DIR --delete --verbose;
          bye
        "